export const icons = {
  home: require("@/assets/icons/homeActive.png"),
  profile: require("@/assets/icons/profile.png"),
  medicines: require("@/assets/icons/medicines.png"),
  appointment: require("@/assets/icons/appointment.png"),
  bell: require("@/assets/icons/bellIcon.png"),
  cart: require("@/assets/icons/cartIcon.png"),
  location: require("@/assets/icons/locationIcon.png"),
  stethoscope: require("@/assets/icons/stethoscopeIcon.png"),
  call: require("@/assets/icons/callIcon.png"),
  calender: require("@/assets/icons/calendarIcon.png"),
  clock: require("@/assets/icons/clockIcon.png"),
  search: require("@/assets/icons/search.png"),
  filter: require("@/assets/icons/filter.png"),
  line: require("@/assets/icons/line.png"),
  consulting : require("@/assets/icons/consulting.png"),
  visitDoctor : require("@/assets/icons/VisitDoctor.png"),
  hospital : require("@/assets/icons/hospital.png"),
};
