export const images ={
    hightLightTab : require("@/assets/images/hightlightTab.png"),
    sliderImg1 : require("@/assets/images/Slider/SliderImg1.png"),
    docter : require("@/assets/images/docter.png"),
    heart : require("@/assets/images/heartImg.png"),
    dental : require("@/assets/images/dental.png"),
    neurology : require("@/assets/images/neurology.png"),
    pediatrics : require("@/assets/images/pediatrics.png"),
    tablet : require("@/assets/images/tablet.png"),
    hospital : require("@/assets/images/hospital.png"),
    profile : require("@/assets/images/profile.png"),
    underline: require("@/assets/images/underline.png"),
    doctor : require("@/assets/images/doctor.png"),
    loginHero : require("@/assets/images/loginHero.png"),
}