export const images ={
    hightLightTab : require("@/assets/images/hightlightTab.png"),
    sliderImg1 : require("@/assets/images/Slider/SliderImg1.png"),
    heart : require("@/assets/images/heartImg.png"),
    dental : require("@/assets/images/dental.png"),
    neurology : require("@/assets/images/neurology.png"),
    pediatrics : require("@/assets/images/pediatrics.png"),
    hospital : require("@/assets/images/hospital.png"),
    profile : require("@/assets/images/profile.png"),
    underline: require("@/assets/images/underline.png"),
    doctor : require("@/assets/images/doctor.png"),
    loginHero : require("@/assets/images/loginHero.png"),
    docter : require("@/assets/images/docter.png"),
    doctor1 : require("@/assets/images/doctor-1.png"),
    doctor2 : require("@/assets/images/doctor-2.png"),
    doctor3 : require("@/assets/images/doctor-3.png"),
    doctor4 : require("@/assets/images/doctor-4.png"),
    doctor5 : require("@/assets/images/doctor-5.png"),
    doctor6 : require("@/assets/images/doctor-6.png"),
    tablet : require("@/assets/images/tablet.png"),
    dolo : require("@/assets/images/tablets/dolo.webp"),
    paracetamol : require("@/assets/images/tablets/paracetamol.webp"),
    amoxycillin : require("@/assets/images/tablets/amoxycillin.webp"),
    betadine : require("@/assets/images/tablets/betadine.jpg"),
    betadinelq : require("@/assets/images/tablets/betadine2.webp"),
    clopidogrel : require("@/assets/images/tablets/clopidogrel.webp"),
    fluconazole : require("@/assets/images/tablets/fluconazole.webp"),
}